[general]
live_config_reload = true

[font]
size = 7.5
normal = { family = "CaskaydiaMono Nerd Font Mono", style = "Regular" }
bold = { family = "CaskaydiaMono Nerd Font Mono", style = "Bold" }
italic = { family = "CaskaydiaMono Nerd Font Mono", style = "Italic" }
bold_italic = { family = "CaskaydiaMono Nerd Font Mono", style = "Bold Italic" }


[window]
decorations = "None"
opacity = 0.80

[colors]
transparent_background_colors = true




